spring:
  profiles:
    active: dev
    
---
server:
  port: 8204

spring:
  profles: dev #开发环境
  application:
      name: microservicecloud-config-client

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
 
 ---
 server:
   port: 8205
 
 spring:
   profles: test #开发环境
   application:
       name: microservicecloud-config-client
 
 eureka:
   client: #客户端注册进eureka服务列表内
     service-url:
       defaultZone: http://eureka-test.com:7001/eureka/     
---
server:
  port: 8203

spring:
  profles: prod #开发环境
  application:
      name: microservicecloud-config-client

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka-prod.com:7001/eureka/